variables:
  TASK:
    value: "docker_image_update"
    options:
      - "docker_image_update"
      - "apt_upgrade"
      - "create_docker_lxc"
    description: "Task to run"

stages:          # List of stages for jobs, and their order of execution
  - prepare
  - parse

clone:
  stage: prepare
  script:
    - git clone https://github.com/haondt/Obsidian.git
    - ls

build-job:       # This job runs in the build stage, which runs first.
  stage: parse
  script:
    - echo "Compiling the code..."
    - ls
    - echo "Compile complete."
    - echo "$CI_PIPELINE_SOURCE"
    - pwd
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

docker-image-update-job:
  stage: parse
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $TASK == "docker_image_update"
  trigger:
    include:
      - local: 'docker-image-update.yml'
