include:
  - local: 'docker-image-update.yml'
variables:
  TASK:
    value: "docker_image_update"
    options:
      - "docker_image_update"
      - "apt_upgrade"
      - "create_docker_lxc"
    description: "Task to run"



stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - echo "$CI_PIPELINE_SOURCE"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

job2:
  extends: docker-job
  rules:
    - if: $TASK == "docker_image_update"