include:
  - local: 'docker-image-update.yml'
variables:
  TASK:
    value: "docker_image_update"
    options:
      - "docker_image_update"
      - "apt_upgrade"
      - "create_docker_lxc"
    description: "Task to run"



stages:          # List of stages for jobs, and their order of execution
  - parse
  - generate
  - trigger
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: parse
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - echo "$CI_PIPELINE_SOURCE"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

this:
  stage: deploy
  script:
    - echo "foo"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $TASK == "docker_image_update"