variables:
  TASK:
    value: "docker_image_update"
    options:
      - "docker_image_update"
      - "apt_upgrade"
      - "create_docker_lxc"
    description: "Task to run"

stages:
  - bootstrap

get-ansible-scripts:
  stage: bootstrap
  script:
    - git clone https://github.com/haondt/Obsidian.git
    - mv Obsidian/docker-automation/gitlab_runner/ansible .
  artifacts:
    name: ansible-scripts
    paths:
      - ansible/
    expire_in: 1 day
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"

docker-image-update-job:
  stage: bootstrap
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $TASK == "docker_image_update"
  trigger:
    include:
      - local: 'docker-image-update.yml'
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
