stages:
  - generate

get-hosts:
  stage: generate
  script:
    - cd ansible
    - ansible-playbook playbooks/upgrade.yml --list-hosts > hosts.txt
    - mv hosts.txt ..
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: get-ansible-scripts
  artifacts:
    name: hosts
    paths:
      - hosts.txt
    expire_in: 1 day

generate:
  stage: generate
  script:
    - cat hosts.txt | python3 generators/apt-upgrade/generator.py > generated-config.yml
  needs:
    - get-hosts
  artifacts:
    paths:
      - generated-config.yml
    expire_in: 1 day

trigger:
  stage: generate
  needs:
    - generate
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
  variables:
    ROOT_PIPELINE_ID: $PARENT_PIPELINE_ID