stages:
  - verify
  - deploy

check-variables:
  stage: verify
  script:
    - "! [[ -z $CONTAINER_SUFFIX ]]"
    - "! [[ -z $CONTAINER_GID ]]"

provision:
  stage: deploy
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: get-ansible-scripts
    - check-variables
  script:
    - cd ansible
    - >-
      ansible-playbook playbooks/create_docker_lxc.yml
      -e "container_suffix=$CONTAINER_SUFFIX"
    - mv lxc.json ..
  artifacts:
    paths:
      - lxc.json
    expire_in: 1 day

setup:
  stage: deploy
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: get-ansible-scripts
    - provision
  script:
    - cd ansible
    - eval $(cat ../lxc.json | python3 generators/create-docker-lxc/ansible-cmd-generator.py $CONTAINER_GID)
    - mv report.txt ..
  artifacts:
    paths:
      - report.txt
    expire_in: 1 day