stages:          # List of stages for jobs, and their order of execution
  - generate
  - trigger

get-containers:
  stage: generate
  script:
    - cd ansible
    - ansible-playbook playbooks/list_docker_containers.yml
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: get-ansible-scripts
  artifacts:
    name: docker-containers
    paths:
      - ansible/containers.yml

generate:
  stage: generate
  script:
    - ls
    - python3 generate.py > generated-config.yml
    - ls
    - git status
    - cat generated-config.yml
  needs:
    - get-containers
  artifacts:
    paths:
      - generated-config.yml
    expire_in: 1 day

trigger:
  stage: trigger
  needs:
    - generate
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate


