docker-image-update-job:
  stage: parse
  script:
    - echo "doing work"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $TASK == "docker_image_update"

generate:
  stage: generate
  needs:
    - docker-image-update-job
  script:
    - python3 generate.py > generated-config.yml
    - git status
    - cat generated-config.yml
  artifacts:
    paths:
      - generated-config.yml
  rules:
    - when: never

trigger:
  stage: trigger
  needs:
    - generate
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate


