stages:          # List of stages for jobs, and their order of execution
  - generate

get-containers:
  stage: generate
  script:
    - cd ansible
    - ansible-playbook playbooks/list_docker_containers.yml
    - mv containers.json ..
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: get-ansible-scripts
  artifacts:
    name: docker-containers
    paths:
      - containers.json

generate:
  stage: generate
  script:
    - cat containers.json | python3 generators/docker-image-update/generator.py > generated-config.yml
  needs:
    - get-containers
  artifacts:
    paths:
      - generated-config.yml
    expire_in: 1 day

trigger:
  stage: generate
  needs:
    - generate
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
  variables:
    ROOT_PIPELINE_ID: $PARENT_PIPELINE_ID


