stages:          # List of stages for jobs, and their order of execution
  - generate
  - trigger

generate:
  stage: generate
  script:
    - python3 generate.py > generated-config.yml
    - git status
    - cat generated-config.yml
  artifacts:
    paths:
      - generated-config.yml

trigger:
  stage: trigger
  needs:
    - generate
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate


