docker-image-update-job:
  stage: parse
  script:
    - echo "doing work"

generate:
  stage: generate
  needs: ["docker-image-update-job"]
  script:
    - python3 generate.py > generated-config.yml
    - git status
    - cat generated-config.yml
  artifacts:
    paths:
      - generated-config.yml

trigger:
  stage: trigger
  needs:
    - generate
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate


